// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IncludeMinimizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "IncludeMinimizer.b6db3f9a-e033-4605-82de-65628de5c510";
        public const string Name = "Include Minimizer";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Ilya Doroshenko";
        public const string Tags = "";
    }
}
