// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IncludeMinimizer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string IncludeMinimizerString = "90a4b8f6-d482-46cc-aeed-33554da13203";
        public static Guid IncludeMinimizer = new Guid(IncludeMinimizerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IMGroup = 0x0001;
        public const int GenMap = 0x0100;
    }
}